# Generated by Django 5.1.6 on 2025-03-06 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academicyear_status'),
        ('account', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(default='1', max_length=2)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('class_roll', models.CharField(max_length=5, verbose_name='Class Roll Number')),
                ('uni_roll', models.CharField(max_length=10, unique=True, verbose_name='University Roll Number')),
                ('reg_number', models.CharField(max_length=10, unique=True, verbose_name='Registration Number')),
                ('guardian_name', models.CharField(max_length=100, verbose_name="Guardian's Name")),
                ('guardian_contact', models.CharField(max_length=15, verbose_name="Guardian's Contact")),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
