# Generated by Django 5.1.6 on 2025-03-02 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_college_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be Alphanumeric', regex='^[\\w@.+\\-\\/]+$')]),
        ),
    ]
