# Generated by Django 5.1.6 on 2025-03-03 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
    ]
