# Generated by Django 5.1.6 on 2025-03-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_student_uni_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='student/documet/'),
        ),
        migrations.AddField(
            model_name='student',
            name='age_proof',
            field=models.FileField(blank=True, null=True, upload_to='student/documet/'),
        ),
    ]
