# Generated by Django 5.1.6 on 2025-03-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='is_admission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fees',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
