# Generated by Django 5.1.6 on 2025-03-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_fees_is_admission_fees_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fees',
        ),
    ]
