# Generated by Django 5.1.6 on 2025-03-05 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academicyear'),
        ('payment', '0002_fees'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fees',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fees',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
        ),
        migrations.AlterUniqueTogether(
            name='fees',
            unique_together={('due_date', 'particular', 'course', 'year')},
        ),
    ]
