# Generated by Django 5.1.6 on 2025-03-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academicyear_status'),
        ('payment', '0003_alter_fees_unique_together_fees_year_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fees',
            unique_together={('due_date', 'course', 'year')},
        ),
        migrations.AddField(
            model_name='fees',
            name='data',
            field=models.JSONField(default=None),
        ),
        migrations.RemoveField(
            model_name='fees',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='fees',
            name='particular',
        ),
    ]
