# Generated by Django 5.1.6 on 2025-03-05 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('eligibility', models.TextField(blank=True, null=True)),
                ('max_year', models.IntegerField(verbose_name='Duration Year')),
                ('max_month', models.IntegerField(blank=True, null=True, verbose_name='Duration Month')),
                ('level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('Diploma', 'Diploma'), ('PhD', 'Doctorate')], default='UG', max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.department')),
            ],
        ),
    ]
