# Generated by Django 5.1.6 on 2025-03-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_remove_academicyear_status_remove_academicyear_title_and_more'),
        ('pay', '0004_delete_fees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicYear',
        ),
    ]
